### ISSUE TITLE
Add hall of fame to readme.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#10]
Add HALL of FAME to readme file

`[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/0)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/0)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/1)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/1)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/2)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/2)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/3)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/3)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/4)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/4)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/5)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/5)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/6)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/6)[![](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/images/7)](https://sourcerer.io/fame/arshadkazmi42/arshadkazmi42/android-contacts-scifiui/links/7)`

Add the above piece of code to README.md file with a title `Contributors`

**Comment by coderquill** [comment]
Hey @arshadkazmi42 , I would like to work on this!

**Comment by coderquill** [comment]
I just have to add the given part at the end of README.md under Contributors , right?

**Comment by arshadkazmi42** [comment]
@coderquill yes. correct!!

**Comment by coderquill** [comment]
Thanks @arshadkazmi42. I have raised a PR accordingly. Can you please review it?

**Comment by arshadkazmi42** [comment]
Cool. I will review it right away
