### ISSUE TITLE
Change app launcher icon

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#12]
@GnikDroy has created a new launcher icon for us, we would want to add it to the app as launcher icon.

I am attaching icons here,

[contacts-app.zip](https://github.com/arshadkazmi42/android-contacts-scifiui/files/2410945/contacts-app.zip)

Basically mipmap folders in the zip needs to be merged with the mipmap folders of the android codebase.

**Comment by arshadkazmi42** [comment]
merged PR #14

**Comment by pshkrh** [comment]
Hi, can I work on this issue?

**Comment by arshadkazmi42** [comment]
@pshkrh Yes. Go ahead and create a PR
