### ISSUE TITLE
Add new app logo to readme file 

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#13]
New app logo needs to be added at the top of the README file.
Something like this

https://github.com/arshadkazmi42/general-feedback/blob/master/README.md

First this image needs to be uploaded in assets directory, this directory does not exist and needs to be created.
Then add the image in that directory with some relevant name like `logo.png`

After doing that, at the top of the README.md file, add the image using below code

`<p align="center"><a href="https://github.com/arshadkazmi42/android-contacts-scifiui"><img src="assets/logo.png" width="150"/></a></p> `

You might need to modify this `src="assets/logo.png"` in above code based on the directory & filename

**Comment by DamonClark** [comment]
I would like to work on this!

**Comment by arshadkazmi42** [comment]
Thanks @DamonClark for taking this up. Go ahead and create a PR

**Comment by DamonClark** [comment]
Does a new image logo need created? Or do I just simply need to add an existing image into the readme?

**Comment by arshadkazmi42** [comment]
Oh. my bad. I forgot to upload the image here. let me upload it right away

**Comment by arshadkazmi42** [comment]
![playstore-icon](https://user-images.githubusercontent.com/4654382/45967846-d34ebb80-c04c-11e8-98d6-61e17fc749e8.png)

You can use this image

**Comment by arshadkazmi42** [comment]
Let me know, if you need anything else
