### ISSUE TITLE
Add Code Quality Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#19]
Add Code Quality badge next to downloads badge in README file

just copy the below code and add it in readme below app name

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/1b7403651c6d4406ad81b29404841940)](https://www.codacy.com/app/arshadkazmi42/android-contacts-scifiui?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/android-contacts-scifiui&amp;utm_campaign=Badge_Grade)`

**To work on this**
1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.

**Note:** Anyone who is not following above two steps, their PR will be rejected

**Comment by thecoderkd** [comment]
Can I work on this?

**Comment by arshadkazmi42** [comment]
@thecoderkd go ahead if this is your first PR in this repo

**Comment by thecoderkd** [comment]
In this PR? Yes. But it's not technically my first one on github, can I still do it?

**Comment by arshadkazmi42** [comment]
yes.

**Comment by thecoderkd** [comment]
Cool. On it :D

**Comment by thecoderkd** [comment]
Hey I have to add it just below ```<h4 align="center">Contacts manager app, with a Scifi UI</h4>```. Right?

**Comment by arshadkazmi42** [comment]
yes. and try to keep it in center

**Comment by thecoderkd** [comment]
![image](https://user-images.githubusercontent.com/18112554/46311420-bf243480-c5df-11e8-9092-687835fb7c45.png)
Any idea why it's showing up like this?
