### ISSUE TITLE
Add runtime permissions

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#2]
App does not asks for contacts access permission and does not works until permission is given manually by going to app settings.

Need to add asking for runtime permission on app launch.

**Comment by knightcube** [comment]
May I work on this issue? I am thinking of adding Dexter permissions library.

**Comment by arshadkazmi42** [comment]
@knightcube yes please. go ahead and create a PR.
Dexter library looks good.

**Comment by djcass44** [comment]
Hey, I opened a pull request to fix this: #16
It uses only native android code, no libraries involved!

**Comment by sankalpchauhan-me** [comment]
I have opened a PR for this #18

**Comment by arshadkazmi42** [comment]
@sankalpchauhan-me @djcass44 has already created a pr for this. you might wanna look at some other issues.

**Comment by sankalpchauhan-me** [comment]
No Problem @arshadkazmi42 

> @sankalpchauhan-me @djcass44 has already created a pr for this. you might wanna look at some other issues.

**Comment by sankalpchauhan-me** [comment]
No problem @arshadkazmi42, will continue to contribute to this project for any new issues.

> @sankalpchauhan-me @djcass44 has already created a pr for this. you might wanna look at some other issues.

**Comment by prateekvijayvergiya** [comment]
If this issue is fixed then kindly close this.

**Comment by arshadkazmi42** [comment]
@prateekvijayvergiya Thanks for reminding. I completely forgot about this.
