### ISSUE TITLE
Rename Screenshots to assets

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#22]
In our repo we have a `Screenshots` directory, we want to rename it to `assets`

This change also needs updating the URL of the image in the README file.

**Steps to work on**
- Add a comment here if you are working on it.
- Create PR.
- Work on a feature branch, do not work on the master branch
- No duplicate PRs
- First Contributor to comment here gets to work on this

**Comment by AMosa3d** [comment]
Hey, may i start working?

**Comment by sebastiaanspeck** [comment]
I'll take it. Expect a commit in a few mins.

**Comment by KUNAL1612** [comment]
This is my first time contributing to an open source project. Can I start working? It doesn't matter if it's solved already. I just want to give it a shot.

**Comment by arshadkazmi42** [comment]
@sebastiaanspeck @KUNAL1612 , @AMosa3d  has commented first, so he will get the issue. 
@sebastiaanspeck @KUNAL1612 you can check my other repos for more beginner issues

**Comment by sebastiaanspeck** [comment]
I'm sorry, but I already created a PR which fixes it

**Comment by arshadkazmi42** [comment]
@sebastiaanspeck I told @AMosa3d is getting this. I have written steps to follow. If @AMosa3d is not going to work on this, then I can accept your PR

**Comment by sebastiaanspeck** [comment]
Tell me which open issues you got on a certain repo. I don't have the time to look in all your 74 repo's to check if there are any open issues without someone doing it.

TIP: assign someone to the issue.

**Comment by AMosa3d** [comment]
@arshadkazmi42 Just give me 10 more minutes, i am still new and i am trying :D

**Comment by arshadkazmi42** [comment]
@AMosa3d Take your time, there is no hurry. I just needed a confirmation.

**Comment by arshadkazmi42** [comment]
> Tell me which open issues you got on a certain repo. I don't have the time to look in all your 74 repo's to check if there are any open issues without someone doing it.
> 
> TIP: assign someone to the issue.

I don't have 74 repos. I contribute in other projects, most of them are forked repos. You can check my own top repos.

**Comment by AMosa3d** [comment]
I have done it, thanks a lot, it's kinda sad i have taken a lot of time, anyway i hope i did it well. Thanks a lot again :D
