### ISSUE TITLE
Create app logo

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#3]
App needs a logo to be used as app launcher, at present app does not have any logo and using android default launcher as app icon.

Launcher icon needs to match with the app design as in snapshots in readme.md file

**Comment by GnikDroy** [comment]
Do you want anything to be included in the logo? [Here](https://ibb.co/buFAe9) is a sample that I have come up with. I have used the colors from your app values so that it matches the feel for the app. 

An alien seemed like a good idea to represent people since this is a sci-fi contact app. 
<p align="center"> <img src="https://image.ibb.co/eFsCsU/my_logo_2.png"> </p>

**Comment by arshadkazmi42** [comment]
@GnikDroy Thank you for taking this up.

This icon looks good. 
I think color looks a bit different from the theme color. 
You can get the color code from the colors.xml file in the codebase.

**Comment by GnikDroy** [comment]
How about this?
I used the textPrimary color from your colors.xml file. #07a79c

<img src="https://image.ibb.co/ijkAe9/mylogofinal.png" alt="mylogofinal" border="0">

**Comment by arshadkazmi42** [comment]
Both looks almost same. 
Lets make it as app launcher and also add it in readme something like this 
https://github.com/arshadkazmi42/general-feedback/blob/master/README.md
on top of the readme

**Comment by arshadkazmi42** [comment]
@GnikDroy can you share the assets of the file, if you are not going to work on this.

**Comment by GnikDroy** [comment]
Yeah. I might be busy for some time. The core alien face is in a SVG file [here](https://ufile.io/m538y). If you want to build the logo in vector form, then there it the vector file. The antennas are a couple of circles and lines and you can add them as you wish. The png extract, on the other hand, can be found [here](https://ufile.io/r6vmc).

**Comment by arshadkazmi42** [comment]
@GnikDroy , thanks for all the work you have done. I have generated launcher icons, I will create a new task to add it in the app. Thanks again
