### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#7]
add code of conduct like this

https://github.com/arshadkazmi42/general-feedback/blob/master/CODE_OF_CONDUCT.md

We need the same code of conduct for this repo also, the code of conduct can be copied and pasted here with the same file name

**Comment by GnikDroy** [comment]
I will do this :)

**Comment by arshadkazmi42** [comment]
Thank you @GnikDroy  for taking this up

**Comment by arshadkazmi42** [comment]
Merged this in #9
